INSERT INTO MC_USER (ID,NAME, LOGIN, PASSWORD, EMAIL) VALUES (1,'Lerry Augusto', 'Lerry1997', '1234', 'lerry@gmail.com');
INSERT INTO MC_USER (ID,NAME, LOGIN, PASSWORD, EMAIL) VALUES (2,'Gabriela', 'gaby123', '1234', 'gaby@gmail.com');

ALTER SEQUENCE MC_USER_ID_SEQ RESTART WITH 2;

INSERT INTO MC_PROFILE (ID,DESCRIPTION) values (1, 'Administrador');
INSERT INTO MC_PROFILE (ID,DESCRIPTION) values (2, 'Usuário');
INSERT INTO MC_PROFILE (ID,DESCRIPTION) values (3, 'Cliente');

ALTER SEQUENCE MC_PROFILE_SEQ RESTART WITH 2;